const express = require('express');
const routes = express.Router();
const baidangRoutes = require('./baidang');
const baidang_anhRoutes = require('./baidang_anh');
const baocaoRoutes = require('./baocao');
const binhluanbaidangRoutes = require('./binhluanbaidang');
const chitietdonhangRoutes = require('./chitietdonhang');
const danhgiaRoutes = require('./danhgia');
const danhmucRoutes = require('./danhmuc');
const dichvuthueRoutes = require('./dichvuthue');
const donhangRoutes = require('./donhang');
const giohangRoutes = require('./giohang');
const likebaidangRoutes = require('./likebaidang');
const loaibaidangRoutes = require('./loaibaidang');
const nguoidungRoutes = require('./nguoidung');
const nguoidungvoucherRoutes = require('./nguoidungvoucher');
const sukienRoutes = require('./sukien');
const thanhtoanRoutes = require('./thanhtoan');
const thongbaoRoutes = require('./thongbao');
const tinnhanRoutes = require('./tinnhan');
const tinnhanaiRoutes = require('./tinnhanai');
const tonkhoRoutes = require('./tonkho');
const voucherRoutes = require('./voucher');
const xacthuc = require('./xacthuc');
const quanHeBanBeRoutes = require('./quanHeBanBe');

routes.use('/baidang', baidangRoutes);
routes.use('/baidang_anh', baidang_anhRoutes);
routes.use('/baocao', baocaoRoutes);
routes.use('/binhluanbaidang', binhluanbaidangRoutes);
routes.use('/chitietdonhang', chitietdonhangRoutes);
routes.use('/danhgia', danhgiaRoutes);
routes.use('/danhmuc', danhmucRoutes);
routes.use('/dichvuthue', dichvuthueRoutes);
routes.use('/donhang', donhangRoutes);
routes.use('/giohang', giohangRoutes);
routes.use('/likebaidang', likebaidangRoutes);
routes.use('/loaibaidang', loaibaidangRoutes);
routes.use('/nguoidung', nguoidungRoutes);
routes.use('/nguoidungvoucher', nguoidungvoucherRoutes);
routes.use('/sukien', sukienRoutes);
routes.use('/thanhtoan', thanhtoanRoutes);
routes.use('/thongbao', thongbaoRoutes);
routes.use('/tinnhan', tinnhanRoutes);
routes.use('/tinnhanai', tinnhanaiRoutes);
routes.use('/tonkho', tonkhoRoutes);
routes.use('/voucher', voucherRoutes);
routes.use('/xacthuc', xacthuc);
routes.use('/quanHeBanBe', quanHeBanBeRoutes);
module.exports = routes;
